name: PlayEffect
main: me.fromgate.playeffect.PlayEffect
version: 0.0.1
website: http://fromgate.me
author: fromgate, fromgate@gmail.com
softdepend: [Vault,Towny,WorldGuard]
commands:
   playeffect:
      aliases: [play,pef,pe]
      description: 
      usage: 
           /playeffect help